{% set name = "pydlm" %}
{% set version = "0.1.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydlm-{{ version }}.tar.gz
  sha256: 312071a2b086090203dde04a60c34f9a3f562e7578dd8ac594a076049718bb99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base

test:
  imports:
    - pydlm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wwrechard/pydlm
  summary: A python library for the Bayesian dynamic linear model for time series modeling
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
